import flet as ft
from catppuccin import PALETTE

mocha = PALETTE.mocha.colors


def get_catppuccin_theme() -> ft.ColorScheme:
    return ft.ColorScheme(
        primary=mocha.mauve.hex,
        on_primary=mocha.base.hex,
        primary_container=mocha.surface0.hex,
        on_primary_container=mocha.mauve.hex,
        secondary=mocha.pink.hex,
        on_secondary=mocha.base.hex,
        secondary_container=mocha.surface0.hex,
        on_secondary_container=mocha.pink.hex,
        tertiary=mocha.teal.hex,
        on_tertiary=mocha.base.hex,
        tertiary_container=mocha.surface0.hex,
        on_tertiary_container=mocha.teal.hex,
        error=mocha.red.hex,
        on_error=mocha.base.hex,
        error_container=mocha.surface1.hex,
        on_error_container=mocha.red.hex,
        surface=mocha.base.hex,
        on_surface=mocha.text.hex,
        on_surface_variant=mocha.subtext0.hex,
        surface_dim=mocha.mantle.hex,
        surface_bright=mocha.surface1.hex,
        surface_container_lowest=mocha.crust.hex,
        surface_container_low=mocha.mantle.hex,
        surface_container=mocha.base.hex,
        surface_container_high=mocha.surface0.hex,
        surface_container_highest=mocha.surface1.hex,
        surface_tint=mocha.mauve.hex,
        outline=mocha.overlay0.hex,
        outline_variant=mocha.surface2.hex,
        inverse_surface=mocha.text.hex,
        on_inverse_surface=mocha.base.hex,
        inverse_primary=mocha.base.hex,
        primary_fixed=mocha.mauve.hex,
        primary_fixed_dim=mocha.mauve.hex,
        on_primary_fixed=mocha.base.hex,
        on_primary_fixed_variant=mocha.surface0.hex,
        secondary_fixed=mocha.pink.hex,
        secondary_fixed_dim=mocha.pink.hex,
        on_secondary_fixed=mocha.base.hex,
        on_secondary_fixed_variant=mocha.surface0.hex,
        tertiary_fixed=mocha.teal.hex,
        tertiary_fixed_dim=mocha.teal.hex,
        on_tertiary_fixed=mocha.base.hex,
        on_tertiary_fixed_variant=mocha.surface0.hex,
        scrim=mocha.crust.hex,
        shadow=mocha.crust.hex,
    )
